### ISSUE TITLE
SMasks are missing for non-raster masking

### ISSUE THREAD

**Issue by doctormo** [jpakkane/capypdf#50]
If the Soft Mask is a vector, it can not currently be encoded using capypdf's API as masking is assumed to always be raster.

The suggested fix I'll be using is to add SMask options to transparency groups and following the pdf specification from there. The goal is transparent gradients like this one produced by Cairo:

[grat_t.pdf](https://github.com/user-attachments/files/17961618/grat_t.pdf)

**Comment by jpakkane** [comment]
>  add SMask options to transparency groups

I'm confused. According to the PDF spec and the sample file, the SMask definition goes to the graphics state object, not to transparency groups. Was this a typo or am I missing something?

**Comment by doctormo** [comment]
Sorry for the confusion. The Transparency group is an input. Let me show in an pull request...

**Comment by doctormo** [comment]
I wanted to share a preview pdf @jpakkane so you can see some of the exciting results of getting this all working:

[stars.pdf](https://github.com/user-attachments/files/17964350/stars.pdf)

**Comment by doctormo** [comment]
Wow that looks much worse in firefox then it does is KDE's Spectical or Gnome's PDf viewer. I wonder if one of my points is wrong in the mesh or if Firefox just doesn't do Type6 gradient patches correctly.

**Comment by jpakkane** [comment]
That looks pretty darn good indeed. I tested it with a bunch of viewers. Acrobat Reader displays it "as expected" and in the same way as Okular. The only weird thing is the white patch at top left. Is it intentional?

Apple Preview botches the whole thing up. The circular halos on stars are flat blue disks and the entire background gradient is upside down.

Trying to convert it to black and white with Ghostscript produces complete garbage, as in it even gets the page size wrong.

In cases like these I tend to trust Acrobat Reader the most. It is, after all, the most common way how printing plates are created (AFAIK anyway). From my experience PDF.js tends to get buggy when you venture in the less common parts of the PDF spec.

**Comment by doctormo** [comment]
That top point is wrong, probably a handle and control point is flipped. Interesting results, the mesh patches might be the most problematic, but good to know adobe is doing the job.

**Comment by jpakkane** [comment]
I asked a friend who has Acrobat Pro to run a validation check on the file and it reported no errors.

**Comment by jpakkane** [comment]
> That top point is wrong, probably a handle and control point is flipped.

A possibility that came to mind is whether it could it be caused by an overflow? That is, the uint conversion goes wrong and instead of `0xFFFFFFFF` it goes to `0x0`?
